### ISSUE TITLE
Assign support S-based paths

### ISSUE THREAD

**Issue by kurtbrose** [mahmoud/glom#60]
would be handy if Assign could take S-based paths as well as T-based

```
>>> glom({}, Assign(T['foo'], 'bar'))
{'foo': 'bar'}
```

it seems intuitive that Assign(S...) would work the same way:

```
>>> glom({}, (Assign(S['foo'], 'bar'), S['foo']))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\kurt\workspace\glom\glom\mutable.py", line 100, in __init__
    path = Path(path)
  File "c:\users\kurt\workspace\glom\glom\core.py", line 277, in __init__
    % sub_parts[0])
ValueError: path segment must be path from T, not T
```

**Comment by kurtbrose** [comment]
ran into this again +1 I should do this

```
>>> glom((), ([Assign(S['results'][T['Tags']['Value']], T['NoncurrentVersionExpiration']['NoncurrentDays'])], S['results']), scope={'results': {}})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\kurt\workspace\glom\glom\mutable.py", line 100, in __init__
    path = Path(path)
  File "c:\users\kurt\workspace\glom\glom\core.py", line 277, in __init__
    % sub_parts[0])
ValueError: path segment must be path from T, not T
```

**Comment by kurtbrose** [comment]
works now with https://github.com/mahmoud/glom/pull/71
