### ISSUE TITLE
Snippets Data-driven assignment error and question

### ISSUE THREAD

**Issue by jimdibb** [mahmoud/glom#83]
From https://glom.readthedocs.io/en/latest/snippets.html

glom({1:2, 2:3}, Call(dict, args=T.items()) <--- missing a paren, 
glom({1:2, 2:3}, lambda t: dict(t.items()))
glom({1:2, 2:3}, dict)

also crashes when fixed
```
>>> from glom import glom, T, Call
>>> glom({1:2, 2:3}, Call(dict, args=T.items()))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/glom/core.py", line 1446, in glom
    ret = _glom(target, spec, scope)
  File "/usr/local/lib/python3.6/dist-packages/glom/core.py", line 1462, in _glom
    return spec.glomit(target, scope)
  File "/usr/local/lib/python3.6/dist-packages/glom/core.py", line 747, in glomit
    return _eval(self.func)(*args, **kwargs)
TypeError: dict expected at most 1 arguments, got 2
```

I got there because I can't figure out how to transform into a dict where the keys are coming from the data, which is a bunch of dicts in a list (and its data from a JQL response). For ex:

```
{ 'issues' :  [ { 'id': '999999', 'summary': 'this is issue 999999'},
                {'id': '888888', 'summary': 'this is 888888'}
              ]
}

```

I'd like to get this into an new dict that looks like:
`{ '999999': 'this is issue 999999', '888888': 'this is issue 888888' }
`
The data driven example above makes some sense but I can't wrap my head around how to do it in the context of the issues list.

Will go back and try some more .Thanks

**Comment by jimdibb** [comment]
So, the docs still have a problem, but I answered my own question  (*breaks elbow patting own back*)

```
target={ 'issues' :  [ { 'id': '999999', 'summary': 'this is issue 999999'},
                      {'id': '888888', 'summary': 'this is 888888'}]}
spec= ('issues', lambda t: dict([tuple([x['id'], x['summary']])for x in t]))
glom(target, spec)
>> {'999999': 'this is issue 999999', '888888': 'this is 888888'}

```

If there is a better solution, it would be interesting to see it. Thanks.

**Comment by mahmoud** [comment]
OK, so, first things first, with the snippet, you're absolutely right. There's a missing paren. Two in fact!

I'm not sure @kurtbrose's intention, but I believe that line is supposed to read:
```python
glom({1:2, 2:3}, Call(dict, args=(T.items(),)))
```

Because args is supposed to be a tuple. I think maybe this example could use some more elaboration. All three lines do the same thing, is that what this is demoing?

---

As for your particular (and more interesting example), I think you're close to optimal at the moment. What we're planning to do to make this better is allow explicit Specs as keys on dicts. Then, maybe add `Flatten` or `Fold` support for dicts, so we could get to a spec like this:

```python
# hypothetical, doesn't work yet
spec = ('issues', [{Spec('id'): 'summary'}], Flatten())
glom(target, spec)
# {'999999': 'this is issue 999999', '888888': 'this is 888888'}
```
How's that look for ya?

**Comment by jimdibb** [comment]
Great, thanks a lot!

**Comment by kurtbrose** [comment]
not to necro the old thread, but we just had a release that added `Fill` which solves this more neatly:

```python
target={ 'issues' :  [ { 'id': '999999', 'summary': 'this is issue 999999'},
                      {'id': '888888', 'summary': 'this is 888888'}]}
spec= ('issues', [Fill((T['id'], T['summary']))], dict)
glom(target, spec)
>> {'999999': 'this is issue 999999', '888888': 'this is 888888'}

```
